import:
  ./Box:
    default: Box

component:
  FantListItem:
    type: Box
    props:
      backgroundColor: green
      padding: 10
    children: BAR

  FantList:
    type: Box
    props:
      backgroundColor: blue
      padding: 10
    children:
      - type: FantListItem
